//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string CashBoxCount { get; set; }
        public string LogIn { get; set; }
        public string Password { get; set; }
        public int EnterpriseId { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Enterprise Enterprise { get; set; }
    }
}
