//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int ItemId { get; set; }
        public string ClientId { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
