//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseService
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int EnterpriseId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        public virtual Service Service { get; set; }
    }
}
