//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime TakeAwayDate { get; set; }
        public int TotalCost { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int BranchId { get; set; }
        public bool Finished { get; set; }
        public string UserId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
