//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Amount { get; set; }
        public int Category { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public int Likes { get; set; }
        public string PicturePath { get; set; }
        public int EnterpriseId { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
