//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobimarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.EnterpriseServices = new HashSet<EnterpriseService>();
        }
    
        public int Id { get; set; }
        public short Type { get; set; }
        public int Duration { get; set; }
        public decimal Cost { get; set; }
    
        public virtual ICollection<EnterpriseService> EnterpriseServices { get; set; }
    }
}
